#!/usr/bin/env bash
# Install commit-msg hooks for the one-context repo.
#
# Currently installs:
#   - eval_fixture_guard.py — warn (non-blocking) when commits touch
#     features/_evals/ without an [eval-fixture] tag in the message.
#
# Idempotent: re-running overwrites the hook with the latest version.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="${REPO_ROOT}/.git/hooks/commit-msg"
GUARD="${REPO_ROOT}/meta/lint/eval_fixture_guard.py"

if [ ! -f "${GUARD}" ]; then
  echo "[install_hooks] missing ${GUARD}" >&2
  exit 1
fi

# Wrapper: chain to existing commit-msg hook if any (preserve user hooks).
mkdir -p "$(dirname "${HOOK_PATH}")"
cat > "${HOOK_PATH}" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by meta/lint/install_hooks.sh — do not edit by hand.
set -e
REPO_ROOT="$(git rev-parse --show-toplevel)"
python3 "${REPO_ROOT}/meta/lint/eval_fixture_guard.py" "$@" || true
# Pass through to any user-installed hook saved as .git/hooks/commit-msg.local
if [ -x "${REPO_ROOT}/.git/hooks/commit-msg.local" ]; then
  "${REPO_ROOT}/.git/hooks/commit-msg.local" "$@"
fi
HOOK
chmod +x "${HOOK_PATH}"
chmod +x "${GUARD}"

echo "[install_hooks] installed: ${HOOK_PATH}"
echo "[install_hooks] eval_fixture_guard active (warn-only)"
